apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-subscriber
  labels:
    app: streaming-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-subscriber
  template:
    metadata:
      annotations:
        dapr.io/app-id: streaming-subscriber
        dapr.io/enabled: "true"
#        dapr.io/app-port: "5003"
        dapr.io/metrics-port: "9090"
#        dapr.io/log-as-json: "true"
#        dapr.io/log-level: "debug"
#        dapr.io/enable-api-logging: "true"
      #        dapr.io/enable-app-health-check: "true"
      #        dapr.io/app-health-check-path: "/actuator/health"
      labels:
        app: streaming-subscriber
    spec:
      containers:
        - name: streaming-subscriber
          image: bibryam/streaming-subscriber
          ports:
            - containerPort: 5003
