apiVersion: apps/v1
kind: Deployment
metadata:
  name: programmatic-subscriber
  labels:
    app: programmatic-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: programmatic-subscriber
  template:
    metadata:
      annotations:
        dapr.io/app-id: programmatic-subscriber
        dapr.io/enabled: "true"
        dapr.io/app-port: "5002"
        dapr.io/metrics-port: "9090"
#        dapr.io/log-as-json: "true"
#        dapr.io/log-level: "debug"
#        dapr.io/enable-api-logging: "true"
#        dapr.io/enable-app-health-check: "true"
#        dapr.io/app-health-check-path: "/actuator/health"
      labels:
        app: programmatic-subscriber
    spec:
      containers:
        - name: programmatic-subscriber
          image: bibryam/programmatic-subscriber
          ports:
            - containerPort: 5002