apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: declarative-pubsub-orders
spec:
  pubsubname: pubsub
  topic: orders
  routes:
    default: /orders
scopes:
  - declarative-subscriber
