apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: programmatic-subscriber

build:
  tagPolicy:
    inputDigest: { }
  artifacts:
    - image: bibryam/programmatic-subscriber
      docker:
        dockerfile: Dockerfile
  local: {}

manifests:
  rawYaml:
    - ../common/kubernetes/*
    - deploy/*

deploy:
  kubectl: {}
  logs:
    prefix: auto

portForward:
  - resourceType: deployment
    resourceName: programmatic-subscriber
    port: 5002
    localPort: 5002
  - resourceType: deployment
    resourceName: programmatic-subscriber
    port: 9090
    localPort: 5012
  - resourceType: deployment
    resourceName: programmatic-subscriber
    port: 3500
    localPort: 3502